### ISSUE TITLE
Error at npm start

### ISSUE THREAD

**Issue by Stonetatara** [jlhernando/index-coverage-extractor#5]
Hi Jose,

I'm a newbie, I'm trying to launch your script on Windows 10, I encoutered somes issues,
My setup:
Windows 10
Node Js v16.13.0
Git  version 2.46.0

I directly DL the script from Github directory.
When I launched the npm start command, I've this issue
```
> index-coverage-extractor@2.0.0 start
> node index

node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:readline/promises
    at new NodeError (node:internal/errors:371:5)
    at ESMLoader.builtinStrategy (node:internal/modules/esm/translators:276:11)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)
    at async link (node:internal/modules/esm/module_job:67:21) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}
```

Do you know why I have thi smessage and can't launch your script?
Thank you

**Comment by jlhernando** [comment]
Did you use "npm install" first to install all the necessary modules?

**Comment by Stonetatara** [comment]
> Did you use "npm install" first to install all the necessary modules?

Hi,
thank your for replying: yes I used "npm install", I followed all the instructions in your post.

I deleted all the forward installation and started again, I got a new error message

```
PS C:\Pro\Dev\GSC\index-coverage-extractor> npm start

> index-coverage-extractor@2.0.0 start
> node index

node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

**Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'playwright' imported from C:\Pro\Dev\GSC\index-coverage-extractor\index.js**
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:884:9)
    at moduleResolve (node:internal/modules/esm/resolve:929:18)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
```
There is a new line of error about Playwright :  '**Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'playwright' imported from C:\Pro\Dev\GSC\index-coverage-extractor\index.js'**

**Comment by Stonetatara** [comment]
Update: 
I manually recovered the missing directory - ‘node_modules’, copied it and re launched 

Same error that the first time
PS C:\Pro\Dev\GSC\index-coverage-extractor> npm start

> index-coverage-extractor@2.0.0 start
> node index

```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:readline/promises
    at new NodeError (node:internal/errors:371:5)
    at ESMLoader.builtinStrategy (node:internal/modules/esm/translators:276:11)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)
    at async link (node:internal/modules/esm/module_job:67:21) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
```

**Comment by jlhernando** [comment]
Can you upgrade your version of Node? Latest would be good with this I think but at least v19

**Comment by Stonetatara** [comment]
Hi, I've just updated the Node version from 19.xx to 22.xx and relaunched your script: that is much better! :)
Te script went through to the end, but I still got an error at the end of the script execution:

```
Sitemap CSV outputs created!
file:///C:/Pro/Dev/index-coverage-extractor-master/index.js:176
      const headers = Object.keys(arr[0]).map((name) => ({ name, filterButton: true, width: 32 }));
                             ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at createExcelTab (file:///C:/Pro/Dev/index-coverage-extractor-master/index.js:176:30)
    at file:///C:/Pro/Dev/index-coverage-extractor-master/index.js:469:7

Node.js v22.9.0
```
3 of the 4 output csv file are empty (0 ko) : 
coverage_XXX-10-11-2024.csv 117ko
sitemaps-xxx_10-11-2024.csv 0ko
summary_xxx_10-11-2024.csv 1ko
sum-sitemaps-xxx_10-11-2024.csv 0 ko

I don"t know if it is "normal", but I have some data, that's much better :)
Hope to ear from you soon
Thank you

**Comment by GalihNugraha22** [comment]
try to fix with this script

1
> npm cache clean -force

2
> rm -rf node_modules

3
> npm install node

4
> npm start

**Comment by jlhernando** [comment]
Cannot convert undefined or null to object bug (Excel module) - Fixed
